import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FCA74C',
    },
    sideBarIcon:{
      width:50,
      height:50,
      marginLeft:10,
      marginTop:10,
    },
    idContainer:{
      marginTop:100,
      flexDirection:'row',
      justifyContent:'center',
    },
    idInput:{
      width:170,
      height:45,
      backgroundColor:"#FFDAB3",
      borderRadius:15,
      fontSize:18,
      color:'black',
      fontWeight:'bold',
      marginRight:10,
    },
    idCheckButton:{
      width:30,
      height:45,
      backgroundColor:"#FCA74C",
      borderColor:"#FFDAB3",
      borderWidth:3,
      borderRadius:10,
      alignSelf:'center',
      alignItems:'center'
    },
    idCheckButtonText:{
      marginTop:2,
      color:'black',
      fontSize:12,
      fontWeight:'bold',
    },
    pwdContainer:{
      marginTop:20,
      width:220,
      height:45,
      alignSelf:"center",
      backgroundColor:"#FFDAB3",
      borderRadius:15,
    },
    input:{
      alignSelf:"center",
      fontSize:18,
      color:'black',
      fontWeight:'bold'
    },
    genderContainer:{
        flexDirection:'row',
        justifyContent:'center',
        alignItems:'center',
        marginTop:15,
    },
    manButton:{
        width:100,
        height:45,
        borderRadius:15,
        backgroundColor:'#FFDAB3',
        borderColor:'#FFDAB3',
        justifyContent:'center',
        alignItems:'center',
        marginRight:20,
    },
    womanButton:{
        width:100,
        height:45,
        borderRadius:15,
        backgroundColor:'#FFDAB3',
        justifyContent:'center',
        alignItems:'center',
    },
    manText:{
        marginBottom:5,
        fontSize:15,
        color:'black',
        fontWeight:'bold',
    },
    womanText:{
        marginBottom:5,
        fontSize:15,
        color:'black',
        fontWeight:'bold',
    },
    selectedGender:{
      backgroundColor:'#ffda6b',
    },
    checkDisableContainer:{
      flexDirection:'row',
      justifyContent:'center',
      alignItems:'center',
      marginTop:30,
    },
    disableButton1:{
      width:65,
      height:35,
      borderRadius:10,
      backgroundColor:'#FFDAB3',
      justifyContent:'center',
      alignItems:'center',
      marginRight:10,
    },
    disableButton2:{
      width:65,
      height:35,
      borderRadius:10,
      backgroundColor:'#FFDAB3',
      justifyContent:'center',
      alignItems:'center',
    },
    disableText:{
      alignSelf:"center",
      fontSize:15,
      color:'black',
      fontWeight:'bold'
    },
    disableETC:{
      marginTop:10,
      width:220,
      height:45,
      alignSelf:"center",
      borderRadius:15,
      marginBottom:30,
      },
    checkDisable:{
      backgroundColor:'#ffda6b',
    },

    joinButton:{
      marginTop:12,
      width:220,
      height:45,
      justifyContent:"center",
      alignSelf:"center",
      backgroundColor:"black",
      borderRadius:15,
    },
    joinButtonText:{
      fontSize:20,
      color:'white',
      alignSelf:'center',
      fontWeight:'bold',
      marginBottom:5,
    },
  });

export default styles;